version: '3'

services:

    vonkrafft-hugo:
        container_name: vonkrafft-hugo
        build: ./.build-hugo
        image: vonkrafft/hugo:latest
        command: [ "server",
            "--bind", "0.0.0.0",
            "--source", "/site",
            "--destination", "/site/public",
            "--buildDrafts", "--buildFuture"]
        ports:
            - "127.0.0.1:1313:1313"
        volumes:
            - .:/site
        restart: unless-stopped
